name: MS Catalogo de Video com Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Iniciando os containeres"
        run: docker-compose -f docker-compose.prod.yml up -d app db redis nginx

      - name: "Aguardando DB"
        run: docker exec -u root -t micro-videos-app wait-for db:3306 -t 120 --

      - name: "Chown in /var/www"
        run: docker exec -u root -t micro-videos-app chown -R www-data:www-data /var/www

      - name: "Rodando composer"
        run: docker exec -t micro-videos-app composer install --no-interaction --prefer-dist --optimize-autoloader -d /var/www/backend

      - name: "Copiando backend .env"
        run: docker exec -t micro-videos-app cp /var/www/backend/.env.example /var/www/backend/.env

      - name: "Copiando backend .env.testing"
        run: docker exec -t micro-videos-app cp /var/www/backend/.env.testing.example /var/www/backend/.env.testing

      - name: "Rodando key:generate"
        run: docker exec -t micro-videos-app php /var/www/backend/artisan key:generate
        
      - name: "Rodando migrations"
        run: docker exec -t micro-videos-app php /var/www/backend/artisan migrate

      - name: "Rodando Phpunit"
        run: docker exec -t micro-videos-app php /var/www/backend/vendor/bin/phpunit -c /var/www/backend/phpunit.xml
